# Author  : Prof. MM Ghassemi <ghassem3@msu.edu>
# Editor : Bailey Bakerson

# Instantiate Ubuntu 20.04
FROM ubuntu:20.04
LABEL maintainer "Bailey Bakerson"
LABEL description="This is an editied docker image for sparty hack"

# Update Ubuntu Software repository
RUN apt update
RUN apt -y install python3-pip
RUN apt -y install vim

# Add the Flask application and install requirements
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Install MySQL and create a database.
#RUN apt -y install mysql-server
#RUN service mysql start
#RUN mysql -e "CREATE DATABASE DB"

# Open ports, set environment variables, start the application.
EXPOSE 8080 
ENV PORT 8080
ENV FLASK_ENV=development
CMD exec python3 app.py
# ----------------------------------------------------- 